## Random Forest on Witconsin Breast Cancer Detection Dataset

In [1]:
# Call the library

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('result.csv')

In [3]:
data.head()

rollno                       name  sub1  sub2  sub3  sub4  sub5  lab1  \
0  71901204L   ADITYA SOMANI                70    64    57    50    63    36   
1  71901208C   AGAWANE PRANITA PRAKASH      32    51    25    49    36     2   
2  71901211C   TAMBOLI AKANKSHA SANTOSH     85    66    77    66    67    35   
3  71901214H   AKSH SARAF                   48    61    45    46    41    23   
4  71901222J   AMLAN KALYAN ROY             74    72    59    65    63    38   

   lab2  lab3 result  
0    44    32   Pass  
1    32    25   Fail  
2    40    41   Pass  
3    28    25   Pass  
4    44    44   Pass

In [4]:
# Output Variable 

y = data.result

In [5]:
# Input Variable

X = data.iloc[:,[2,3,4,5,6,7,8,9]].values

In [6]:
print(X)

[[70 64 57 ... 36 44 32]
 [32 51 25 ...  2 32 25]
 [85 66 77 ... 35 40 41]
 ...
 [47 66 45 ... 27 41 44]
 [47 59 45 ... 27 41 44]
 [67 47 32 ... 36 28 18]]


In [7]:
# Output is in form of a string (string is not used for calculation, convert it into numeric value)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
# Feature Scaling on input data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
# Develop Random Forest  
from sklearn.ensemble import RandomForestClassifier
cls = RandomForestClassifier()
cls.fit(X_train, y_train)

C:\Users\sumit.khandelwal\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [11]:
# FInding out the Predicted value

y_pred = cls.predict([[45,56,56,56,56,23,44,33]])

In [12]:
print(y_pred)

[1]


In [13]:
# Build the confusion matrix 
# Confusion matrix is used to check performance of classification algorithm

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

ValueError: Found input variables with inconsistent numbers of samples: [112, 1]

In [14]:
# Finding out accuracy
from sklearn.metrics import accuracy_score
print("Accuracy of our model is :", accuracy_score(y_test, y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [112, 1]

In [15]:
from sklearn.metrics import classification_report
print("Report of Classification model is : ")
print(classification_report(y_pred, y_test))

Report of Classification model is : 


ValueError: Found input variables with inconsistent numbers of samples: [1, 112]